// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c524826b-6992-45f5-bef4-ce8ba3f22e28",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Lz9DecF86",
    "aws_user_pools_web_client_id": "3egai2962nvc8k11gltgs34h5q"
};


export default awsmobile;
